apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    version: "00001"
    app: nginx
spec:
  revisionHistoryLimit: 10
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginxdemos/hello
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - sleep 20
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: web-internal
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
          - containerPort: 80
            name: web-internal
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: web-internal
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 1536Mi
            requests:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File        
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      serviceAccount: read-pods
      serviceAccountName: read-pods
      terminationGracePeriodSeconds: 60