apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-curl
spec:
  template:
    spec:
      containers:
          - name: nginx-curl
            image: curlimages/curl
            args:
            - /bin/sh
            - -c
            - 'i=0; while true; do curl http://LOAD_BALANCER_ADDRESS; sleep 10; done'
      restartPolicy: Never
  backoffLimit: 4